### ISSUE TITLE
Become an official implementation of Casbin

### ISSUE THREAD

**Issue by hsluoyz** [ngoclinhng/acx#1]
Hi @ngoclinhng ,

I am Yang Luo, the founder of Casbin project. I noticed this lib for several days. First, thanks for making this amazing lib in Elixir !

I'm here to ask, are you willing to let this lib become an official implementation of Casbin for Elixir?

1. This lib will get a new place under official Casbin org: https://github.com/casbin . You can still administrate and develop it.
2. At the same time, you will become a core member of Casbin org and join the whole Casbin community.
3. Of course we will together make this lib better. We are always trying to provide the best and unified user experience for Casbin users on all languages.

Let me know if you are interested, thanks!

**Comment by ngoclinhng** [comment]
Sure I'm all in. Just tell me what I need to do

**Comment by hsluoyz** [comment]
How is Elixir project usually naming? How should we name the Casbin for Elixir project? casbin-ex? or what?

**Comment by ngoclinhng** [comment]
casbin-ex should be fine.

**Comment by hsluoyz** [comment]
I have created the repo: https://github.com/casbin/casbin-ex

Can you move your commits into it? Via direct commits or PR.

**Comment by hsluoyz** [comment]
Any update?

**Comment by hsluoyz** [comment]
Finished: https://github.com/casbin/casbin-ex
